force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Log of an Error on the Salesforce Platform</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}-{YYYY}.{MM}.{DD}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExceptionLog__c/ExceptionLog__c.object-meta.xml
<CustomObject>
    <description>Log a Platform Exception on Salesforce</description>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EXL-{0000}-{YYYY}.{MM}.{DD}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ExceptionLog__c/fields/ErrorLog__c.field-meta.xml
<CustomField>
    <fullName>ErrorLog__c</fullName>
    <label>Error Log</label>
    <referenceTo>ErrorLog__c</referenceTo>
    <relationshipLabel>Exception Logs</relationshipLabel>
    <relationshipName>Exception_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/ExceptionLog__c/fields/ExceptionLog__c.field-meta.xml
<CustomField>
    <fullName>ExceptionLog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exception Log</label>
    <referenceTo>ExceptionLog__c</referenceTo>
    <relationshipLabel>Exception Logs</relationshipLabel>
    <relationshipName>Exception_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RowLog__c/RowLog__c.object-meta.xml
<CustomObject>
    <label>Row Log</label>
    <nameField>
        <displayFormat>RL-{0000}-{YYYY}.{MM}.{DD}</displayFormat>
        <label>Row Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Row Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RowLog__c/fields/ExceptionLog__c.field-meta.xml
<CustomField>
    <fullName>ExceptionLog__c</fullName>
    <label>Exception Log</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ExceptionLog__c.Type__c</field>
            <operation>equals</operation>
            <value>DmlException, EmailException</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ExceptionLog__c</referenceTo>
    <relationshipLabel>Row Logs</relationshipLabel>
    <relationshipName>RowLogs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceLog__c/ServiceLog__c.object-meta.xml
<CustomObject>
    <label>Service Log</label>
    <nameField>
        <displayFormat>SL-{0000}-{YYYY}.{MM}.{DD}</displayFormat>
        <label>Service Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/LoggableException.cls
public virtual class LoggableException extends Exception {
	private ErrorLog__c errorLog;
	private List<ExceptionLog__c> exceptionLogs;
	private List<RowLog__c> rowLogs;
	private List<ServiceLog__c> serviceLogs;

	public ErrorLog__c getErrorLog() { return this.errorLog; }
	public void setErrorLog(ErrorLog__c log) {
		this.errorLog = log;
	}

	public void init(Exception exc) {
		errorLog = new ErrorLog__c();
		exceptionLogs = new List<ExceptionLog__c>();
		rowLogs = new List<RowLog__c>();
		serviceLogs = new List<ServiceLog__c>();

		// initialize logger with the first exception
	}

	public void addException(Exception exc) {
		// add an exception to the error log
	}

	public void flush() {
		// commit all data to salesforce
	}
}